// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $api_keydeleter from "./routes/api/keydeleter.ts";
import * as $api_logout from "./routes/api/logout.ts";
import * as $auth_login from "./routes/auth/login.ts";
import * as $auth_mssignin from "./routes/auth/mssignin.ts";
import * as $index from "./routes/index.tsx";
import * as $login from "./routes/login.tsx";
import * as $signup from "./routes/signup.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $Footer from "./islands/Footer.tsx";
import * as $Navbar from "./islands/Navbar.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/api/keydeleter.ts": $api_keydeleter,
    "./routes/api/logout.ts": $api_logout,
    "./routes/auth/login.ts": $auth_login,
    "./routes/auth/mssignin.ts": $auth_mssignin,
    "./routes/index.tsx": $index,
    "./routes/login.tsx": $login,
    "./routes/signup.tsx": $signup,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/Footer.tsx": $Footer,
    "./islands/Navbar.tsx": $Navbar,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
